#################################################################

[[workflow]]
id = 1
active = true

name = "Demo Workflow"
description = "Send a HTTP request with a message and watch that gets logged to standard out"

[workflow.trigger]
variety = "webhook"
urlSuffix = "quickstart"

[workflow.steps.1]
active = true
variety = "stdout"
name = "Log to Standard Out"
description = "This workflow step will show the payload to stdout while showcasing the demo"

#################################################################

[[workflow]]
id = 2
active = true

name = "AFK Bot Workflow"
description = "AFK Bot receives a message from an incoming webhook and posts it to the specified room, if AFK bot is present in that room"

[workflow.trigger]
variety = "webhook"
urlSuffix = "afkbot-8khwd7y1j3hdi8ahsda"

[workflow.steps.1]
active = true
variety = "postMatrixMessage"
name = "post message to Matrix room"
description = "Post message to a matrix room"

[workflow.steps.1.meta]
messagePrefix = "[AFK Alert]"
matrixRoom = "" # Optional but would be overridden if specified in payload

#################################################################
